### PR TITLE
Add some facts about safety with new OAuth phishing

### PR DESCRIPTION
**Pull request by pandaninjas**

### CODE REVIEW

**Comment by KTibow** [comment]
redundant?

**Comment by pandaninjas** [comment]
> redundant?

Sort of. I'll make it into a list of safety facts so it always shows (see discussion in trolling with micro)

**Comment by KTibow** [comment]
wait so do i still merge

**Comment by pandaninjas** [comment]
> wait so do i still merge

Not yet.

**Comment by KTibow** [comment]
since the source one didn't get merged i'm closing this. feel free to add as normal fun facts though.

**Pull request closed without merging**
